---
name: Sample Action
description: Sets an environment variable
runs:
  using: composite
  steps:
  - name: Set default variables
    shell: bash
    run: |
      echo "SAMPLE=FROM INNER ACTION" >> $GITHUB_ENV
  - name: check variables
    shell: bash
    run: |
      echo $SAMPLE
