---
name: Sample Action
description: Sets an environment variable
inputs: 
  name:
    description: Name
    required: true
runs:
  using: composite
  steps:
  - name: Set environment variables
    shell: bash
    run: |
      echo "VALUES=${{ inputs.name }}-$(date +%Y/%m/%d)" >> $GITHUB_ENV
  - name: Set default variables
    shell: bash
    run: |
      echo "SAMPLE=FROM INNER ACTION | $VALUES" >> $GITHUB_ENV
  - name: check variables
    shell: bash
    run: |
      echo $SAMPLE

  - name: Check config exists
    id: check-config
    continue-on-error: true
    shell: bash
    run: |
      if ! test -f ./demo/hola; then
        exit 1
      fi

  - name: Create skel
    if: steps.check-config.outcome == 'failure'
    shell: bash
    run: |
      mkdir -p ./demo
      echo "HOLA" > ./demo/hola
