name: GitOPS Action
on:
  push:
    branches:
      - "none"
jobs:
  commit-to-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Checkout another repo
        uses: actions/checkout@v3
        with:
          repository: mijailr/account
          path: account
          ssh-key: ${{ secrets.DEPLOY_KEY }}
      - name: List files
        run: ls -la account
      - name: Set SAMPLE
        id: sample
        run: |
          echo "CLUSTER_PATH=./account" >> $GITHUB_ENV
          echo "sample=FROM OUTPUTS" >> $GITHUB_OUTPUT
      - name: Get from inner action
        uses: ./.github/actions/with-secrets
        with:
          name: Mijail
      - name: Change file
        run: |
          echo "$SAMPLE" >> ./$CLUSTER_PATH/changes
      - name: Commit and push
        shell: bash
        working-directory: ./${{ env.CLUSTER_PATH }}
        run: |
          git config --global user.name "Github Actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "chore: changed from gitops"
          git push
          
